export type CapabilityState = "VERIFIED" | "SHADOW" | "DISABLED";
export type CapabilityKey = "PLAYER_ROSTER" | "PLAYER_POSITION" | "STARTER_STATUS" | "SUBSTITUTION" | "GOAL" | "PENALTY_GOAL" | "PENALTY_MISS" | "OWN_GOAL" | "YELLOW_CARD" | "RED_CARD" | "MATCH_CLOCK" | "FINAL_SCORE";
export type TxlineCapability = { key: CapabilityKey; state: CapabilityState; parserVersion: string; capturedFixtureIds: string[]; samplePayloadPaths: string[]; verifiedAt: string | null; notes: string };

/** All capabilities start fail-closed until real provider evidence is checked in. */
export const capabilityRegistry: Record<CapabilityKey, TxlineCapability> = Object.fromEntries(([
  "PLAYER_ROSTER", "PLAYER_POSITION", "STARTER_STATUS", "SUBSTITUTION", "GOAL", "PENALTY_GOAL", "YELLOW_CARD", "RED_CARD", "MATCH_CLOCK", "FINAL_SCORE",
] as CapabilityKey[]).map((key) => [key, { key, state: "SHADOW", parserVersion: "unverified", capturedFixtureIds: [], samplePayloadPaths: [], verifiedAt: null, notes: "Awaiting captured TxLINE payload and contract tests." }])) as unknown as Record<CapabilityKey, TxlineCapability>;
capabilityRegistry.PENALTY_MISS = { key: "PENALTY_MISS", state: "DISABLED", parserVersion: "unverified", capturedFixtureIds: [], samplePayloadPaths: [], verifiedAt: null, notes: "Requires verified outcome enum." };
capabilityRegistry.OWN_GOAL = { key: "OWN_GOAL", state: "DISABLED", parserVersion: "unverified", capturedFixtureIds: [], samplePayloadPaths: [], verifiedAt: null, notes: "Requires verified GoalType enum." };
capabilityRegistry.PLAYER_ROSTER = { key: "PLAYER_ROSTER", state: "VERIFIED", parserVersion: "lineup-action-v1", capturedFixtureIds: ["18175981"], samplePayloadPaths: ["tests/provider-fixtures/txline-devnet/scores-snapshot-18175981.json"], verifiedAt: "2026-07-10T15:03:35.981Z", notes: "Captured Action=lineups payload; contract test validates required identity fields." };
capabilityRegistry.PLAYER_POSITION = { key: "PLAYER_POSITION", state: "VERIFIED", parserVersion: "txline-soccer-world-cup-v1", capturedFixtureIds: ["18175981"], samplePayloadPaths: ["tests/provider-fixtures/txline-devnet/scores-snapshot-18175981.json", "docs/txline/provider-notes.md"], verifiedAt: "2026-07-11T00:00:00.000Z", notes: "TxODDS team confirmed World Cup soccer position IDs 34=GK, 35=DEF, 36=MID, 37=FWD under unitId 0." };
capabilityRegistry.STARTER_STATUS = { key: "STARTER_STATUS", state: "VERIFIED", parserVersion: "lineup-action-v1", capturedFixtureIds: ["18175981"], samplePayloadPaths: ["tests/provider-fixtures/txline-devnet/scores-historical-18175981.json"], verifiedAt: "2026-07-11T00:00:00.000Z", notes: "Captured confirmed lineup records provide boolean starter status." };
capabilityRegistry.SUBSTITUTION = { key: "SUBSTITUTION", state: "VERIFIED", parserVersion: "soccer-historical-v1", capturedFixtureIds: ["18175981"], samplePayloadPaths: ["tests/provider-fixtures/txline-devnet/scores-historical-18175981.json"], verifiedAt: "2026-07-11T00:00:00.000Z", notes: "Captured confirmed substitutions resolve PlayerInId and PlayerOutId through player.normativeId." };
capabilityRegistry.GOAL = { key: "GOAL", state: "VERIFIED", parserVersion: "soccer-historical-v1", capturedFixtureIds: ["18175981"], samplePayloadPaths: ["tests/provider-fixtures/txline-devnet/scores-historical-18175981.json", "docs/txline/provider-notes.md"], verifiedAt: "2026-07-11T00:00:00.000Z", notes: "Confirmed goal records with documented GoalType Shot or Head resolve a scorer. Penalty and own-goal capability remain separate and disabled." };
capabilityRegistry.MATCH_CLOCK = { key: "MATCH_CLOCK", state: "VERIFIED", parserVersion: "soccer-historical-v1", capturedFixtureIds: ["18175981"], samplePayloadPaths: ["tests/provider-fixtures/txline-devnet/scores-historical-18175981.json"], verifiedAt: "2026-07-11T00:00:00.000Z", notes: "Captured confirmed actions contain integer Clock.Seconds; final records inherit the greatest observed match clock when omitted." };
capabilityRegistry.FINAL_SCORE = { key: "FINAL_SCORE", state: "VERIFIED", parserVersion: "soccer-historical-v1", capturedFixtureIds: ["18175981"], samplePayloadPaths: ["tests/provider-fixtures/txline-devnet/scores-historical-18175981.json"], verifiedAt: "2026-07-11T00:00:00.000Z", notes: "game_finalised records expose final total goals in Stats keys 1 and 2." };
